-- 0071_补齐数据库对象中文注释.sql：为当前数据库、业务表和字段补齐可审计的中文说明。

DO $$
BEGIN
  EXECUTE format(
    'COMMENT ON DATABASE %I IS %L',
    current_database(),
    'Stock 策略演进系统运行数据库；PostgreSQL 是运行时唯一事实源'
  );
END $$;

CREATE TEMP TABLE _table_comment (
  object_name text PRIMARY KEY,
  description text NOT NULL
) ON COMMIT DROP;

INSERT INTO _table_comment (object_name, description) VALUES
  ('agent_confirmation', 'Agent 高风险工具调用的用户确认请求与决策结果'),
  ('agent_evaluation_run', 'Agent 能力评测运行、配置与结论'),
  ('agent_external_cli_run', 'Agent 外部命令行调用的执行留痕'),
  ('agent_memory_artifact', 'Agent 可复用记忆及其证据、状态与替代关系'),
  ('agent_run_metric', 'Agent 单次运行的令牌、成本、时延与压缩指标'),
  ('agent_setting', 'Agent 单例运行开关与能力设置'),
  ('agent_tool_audit', 'Agent 工具调用参数与结果摘要审计'),
  ('agent_tool_metric', 'Agent 单次工具调用的性能与结果规模指标'),
  ('analysis_run', '领域分析请求、执行状态、结果与数据缺口'),
  ('backtest_run', '回测请求、执行过程、结构化结果与最终研究结论'),
  ('backtest_run_comparison', '回测运行之间的显式比较关系'),
  ('backtest_run_source', '回测运行使用的版本化源码快照'),
  ('chat_attachment', 'Agent 会话上传附件的本地元数据'),
  ('chat_message', 'Agent 会话内按顺序保存的消息'),
  ('chat_session', '用户、任务与回测共用的 Agent 会话'),
  ('chat_session_event', 'Agent 会话生命周期事件'),
  ('content_document', '旧内容库文档主记录'),
  ('content_legacy_import', '旧文件内容导入数据库的来源映射'),
  ('content_revision', '旧内容库文档修订正文与校验摘要'),
  ('daily_plan_auction_assessment', '每日计划候选在次日集合竞价阶段的结构化复核'),
  ('daily_plan_playbook', '每日计划任务生成并在成功后激活的结构化执行预案'),
  ('fundamental_snapshot', '标的在指定日期与报告期的基本面快照'),
  ('hithink_dataset_snapshot', '扶摇扩展数据能力的规范化请求快照与原始结果'),
  ('job_definition', '数据库原生定时作业定义'),
  ('job_prompt', 'Agent 作业提示词主记录'),
  ('job_prompt_revision', 'Agent 作业提示词的不可变修订'),
  ('job_run', '定时或手动作业的单次运行状态与结果'),
  ('job_run_output', 'Agent 作业运行产生的版本化 Markdown 输出'),
  ('llm_model', '可选大语言模型及其能力配置'),
  ('llm_provider', '大语言模型服务商连接配置'),
  ('llm_setting', '当前启用模型的单例设置'),
  ('market_bar', '标的日线、三十分钟线与期货日线行情'),
  ('market_board', '扶摇行业、概念等板块主数据'),
  ('market_board_membership', '板块成分股及其历史有效期'),
  ('market_dragon_tiger_entry', '龙虎榜全部、机构与游资榜单记录'),
  ('market_fetch_run', '单次行情或数据源请求的落库留痕'),
  ('market_indicator_dirty', '需要重算正式指标的行情脏区间'),
  ('market_indicator_run', '正式指标单标的重算的输入与状态留痕'),
  ('market_indicator_value', '按行情主键保存的版本化正式指标结果'),
  ('market_instrument', '股票、指数、板块、基金和期货的统一标的主数据'),
  ('market_instrument_alias', '标的检索使用的名称或代码别名'),
  ('market_limit_event', '涨停、跌停与炸板事件明细'),
  ('market_limit_ladder_snapshot', '指定日期的连板梯队快照'),
  ('market_special_sync_run', '市场特色数据集分页同步的覆盖与状态留痕'),
  ('market_stock_character_metric', '基于正式指标计算的股性与护盘恢复指标'),
  ('market_system_tracking', '系统自动纳入行情跟踪的标的及原因'),
  ('market_trading_day', 'A 股交易日历'),
  ('pool_board_preference', '标的池关注板块的展示顺序'),
  ('pool_membership', '标的在短线或长线池中的角色、评分与关注状态'),
  ('portfolio_account_snapshot', '用户录入或导入的历史账户资产快照'),
  ('portfolio_account_state', '由持仓事件流连续维护的单例资金台账'),
  ('portfolio_position', '当前真实持仓数量、成本与持仓周期状态'),
  ('portfolio_position_change', '真实持仓变动、成交归因与执行纪律记录'),
  ('portfolio_position_snapshot_daily', '当前持仓按交易日生成的估值与止盈止损快照'),
  ('portfolio_realized_pnl_baseline', '累计已实现盈亏的一次性历史基线'),
  ('schema_migrations', '已应用数据库迁移的版本与文件哈希登记'),
  ('script_registry', '旧脚本内容库的脚本主记录'),
  ('script_version', '旧脚本内容库的版本正文与哈希'),
  ('strategy_doc', '旧策略文件登记主记录'),
  ('strategy_document', '当前策略文档主记录与生效修订指针'),
  ('strategy_document_revision', '策略文档的不可变修订正文'),
  ('strategy_evolution_backtest', '策略演进记录与支撑回测的关联'),
  ('strategy_evolution_log', '策略演进讨论、结论与采纳状态'),
  ('strategy_publish_proposal', '等待真实用户审核的策略发布提案'),
  ('strategy_score_benchmark', '策略修订绑定的版本化固定评分基准'),
  ('strategy_state', '当前策略集合哈希与变更序号的单例状态'),
  ('strategy_version', '旧策略内容库的版本正文与哈希'),
  ('system_setting', '服务端私有系统设置与数据源凭据'),
  ('task_definition', '旧任务模板与调度定义'),
  ('task_run', '旧任务运行步骤、产物与缺口记录'),
  ('valuation_snapshot', '标的在指定日期的估值快照'),
  ('volume_snapshot', '完整私有备份或可移植固定资产包的生成记录');

DO $$
DECLARE
  missing_names text;
  item record;
BEGIN
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO missing_names
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN _table_comment description ON description.object_name = c.relname
   WHERE n.nspname = 'public'
     AND c.relkind IN ('r', 'p')
     AND description.object_name IS NULL;
  IF missing_names IS NOT NULL THEN
    RAISE EXCEPTION '数据库表注释词典缺少：%', missing_names;
  END IF;

  FOR item IN
    SELECT c.oid, c.relname, description.description
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN _table_comment description ON description.object_name = c.relname
     WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p')
  LOOP
    IF obj_description(item.oid, 'pg_class') IS NULL THEN
      EXECUTE format('COMMENT ON TABLE public.%I IS %L', item.relname, item.description);
    END IF;
  END LOOP;
END $$;

CREATE TEMP TABLE _column_comment (
  column_name text PRIMARY KEY,
  description text NOT NULL
) ON COMMIT DROP;

INSERT INTO _column_comment (column_name, description) VALUES
  ('action', '计划动作或处置建议'),
  ('active', '是否处于有效状态'),
  ('active_model_id', '当前启用模型标识'),
  ('adjustment', '行情复权方式'),
  ('adjustments', '策略调整项列表'),
  ('adoption_status', '策略演进结论的采纳状态'),
  ('agent', '执行外部命令的 Agent 标识'),
  ('alias', '标的检索别名'),
  ('amount', '金额'),
  ('analysis_type', '领域分析类型'),
  ('anchor_date', '资金台账锚定的账户快照日期'),
  ('api_key', '服务商 API 密钥密文或私有值'),
  ('api_protocol', '服务商 API 协议类型'),
  ('applicability_boundary', '研究结论适用边界'),
  ('applied_at', '迁移应用时间'),
  ('archived', '会话是否已归档'),
  ('args', '工具调用参数'),
  ('args_bytes', '工具调用参数字节数'),
  ('artifacts', '运行产物引用列表'),
  ('as_of_date', '数据事实截止日期'),
  ('assessment_output_id', '竞价复核输出标识'),
  ('assessment_summary', '竞价复核结论摘要'),
  ('attempt_count', '作业已尝试次数'),
  ('attention_from', '近期关注开始日期'),
  ('attention_reason', '近期关注的事实依据'),
  ('attention_until', '近期关注结束日期'),
  ('attribution_note', '成交归因说明'),
  ('auction_md', '集合竞价预案 Markdown'),
  ('backtest_run_id', '关联回测运行标识'),
  ('bar_date', '行情所属交易日期'),
  ('bar_time', '行情时间点'),
  ('base_change_seq', '提案基于的策略变更序号'),
  ('base_revision_id', '修订基于的上一修订标识'),
  ('base_source_run_id', '复用源码的基础回测运行标识'),
  ('base_strategy_hash', '提案基于的策略集合哈希'),
  ('base_url', '服务商 API 基础地址'),
  ('benchmark_code', '固定评分基准业务代码'),
  ('benchmark_tags', '复核使用的基准标签列表'),
  ('board_instrument_id', '板块标的标识'),
  ('board_type', '板块类型'),
  ('buy_amount', '榜单买入金额'),
  ('cache_read_tokens', '缓存读取令牌数'),
  ('cache_write_tokens', '缓存写入令牌数'),
  ('calculation_version', '指标计算版本'),
  ('capabilities', '标的支持的数据能力集合'),
  ('capability', '扶摇数据能力代码'),
  ('cash', '可用现金金额'),
  ('category', '记忆分类'),
  ('change_date', '持仓变动日期'),
  ('change_seq', '策略变更序号'),
  ('change_summary', '本次版本变更摘要'),
  ('channel', '实际使用的数据通道'),
  ('close', '收盘价'),
  ('closed_fetch_run_id', '关闭成分关系的抓取运行标识'),
  ('closed_pnl', '累计已实现盈亏'),
  ('code', '稳定业务代码或标的代码'),
  ('code_cleanup_status', '临时代码清理状态'),
  ('compaction_count', '上下文压缩次数'),
  ('compared_run_id', '被比较的回测运行标识'),
  ('completed_pages', '已完成分页数'),
  ('computed_at', '指标计算完成时间'),
  ('conclusion', '最终结论'),
  ('conclusion_md', '回测结论 Markdown'),
  ('conclusion_status', '回测结论定稿状态'),
  ('conclusion_summary', '回测最终结论摘要'),
  ('config', '作业结构化配置'),
  ('config_snapshot', '回测启动时的配置快照'),
  ('confirmation_id', '关联用户确认记录标识'),
  ('content', '版本化正文或消息内容'),
  ('content_type', '内容文档类型'),
  ('context_compacted_at', '最近一次上下文压缩时间'),
  ('context_summary', '已压缩历史的上下文摘要'),
  ('context_summary_estimated_tokens', '上下文摘要估算令牌数'),
  ('context_summary_through_seq', '上下文摘要覆盖到的消息序号'),
  ('context_window', '模型上下文窗口令牌上限'),
  ('cost_amount', '模型调用成本金额'),
  ('cost_basis', '持仓成本口径说明'),
  ('cost_price', '当前持仓单位成本'),
  ('cost_price_before', '本次卖出前的持仓单位成本'),
  ('coverage_end', '数据覆盖结束日期'),
  ('coverage_start', '数据覆盖开始日期'),
  ('created_at', '记录创建时间'),
  ('cron', 'Cron 调度表达式'),
  ('currency', '计价币种'),
  ('current_hash', '当前策略集合哈希'),
  ('current_revision_id', '当前生效修订标识'),
  ('data', '事件结构化数据'),
  ('data_gaps', '已确认的数据缺口列表'),
  ('data_status', '数据就绪状态'),
  ('data_time', '数据实际时间'),
  ('dataset', '特色数据集代码'),
  ('dataset_type', '榜单数据集类型'),
  ('dea', 'MACD 信号线 DEA'),
  ('debt_ratio', '资产负债率'),
  ('decided_at', '用户决策时间'),
  ('decided_by', '提案决策人标识'),
  ('decision_note', '提案决策说明'),
  ('decision_origin', '交易决策来源'),
  ('defense_break_count', '护盘跌破事件次数'),
  ('defense_recovered_count', '护盘跌破后收回次数'),
  ('defense_recovery_ma10', '相对 MA10 的护盘收回率'),
  ('degraded_from', '发生降级的首选数据通道'),
  ('deviation_reason', '偏离策略或预案的原因'),
  ('dif', 'MACD 快慢线差值 DIF'),
  ('distributions', '各评分特征的经验分布'),
  ('dividend_yield', '股息率'),
  ('doc_id', '关联旧策略文档标识'),
  ('document_id', '关联文档标识'),
  ('document_revision_id', '关联策略文档修订标识'),
  ('duration_ms', '工具调用耗时毫秒数'),
  ('earliest_date', '需要重算的最早行情日期'),
  ('effective_from', '关系生效日期'),
  ('effective_to', '关系失效日期；为空表示当前有效'),
  ('enabled', '是否启用'),
  ('engine_git_commit', '回测引擎 Git 提交哈希'),
  ('engine_path', '回测引擎入口路径'),
  ('engine_sha256', '回测引擎文件 SHA-256'),
  ('entry_auction_assessment_id', '建仓时采用的竞价复核记录标识'),
  ('error_message', '失败错误摘要'),
  ('estimated_history_tokens', '历史消息估算令牌数'),
  ('estimated_system_tokens', '系统提示估算令牌数'),
  ('estimated_tool_definition_tokens', '工具定义估算令牌数'),
  ('evaluation_session_id', '最近一次研究评估会话标识'),
  ('evaluation_summary', '标的研究评估摘要'),
  ('evaluation_version', '评测规则版本'),
  ('event_price', '涨跌停或炸板事件价格'),
  ('event_type', '事件类型'),
  ('evidence', '支撑记忆结论的结构化证据'),
  ('evidence_md', '计划证据 Markdown'),
  ('evolution_id', '关联策略演进记录标识'),
  ('exchange', '交易所代码'),
  ('execution_compliance', '交易执行纪律符合状态'),
  ('execution_origin', '回测执行来源'),
  ('execution_status', '回测执行状态'),
  ('exit_code', '外部命令退出码'),
  ('fetched_at', '数据抓取或落库时间'),
  ('finalized_at', '回测结论定稿时间'),
  ('finished_at', '运行结束时间'),
  ('first_event_time', '首次触发涨跌停事件时间'),
  ('first_text_ms', '首段文本返回耗时毫秒数'),
  ('freq', '行情频率'),
  ('gaps', '抓取、同步或计算缺口列表'),
  ('generation', '脏区间更新代次'),
  ('grade', '策略评级'),
  ('gross_margin', '毛利率'),
  ('headline', '计划条目标题'),
  ('high', '最高价'),
  ('hithink_api_key', '扶摇 API Key；仅服务端读取且接口不回显'),
  ('hypothesis', '回测待验证假设'),
  ('id', '记录主键标识'),
  ('imported_at', '旧内容导入时间'),
  ('indicator_run_id', '关联正式指标运行标识'),
  ('industry_name', '行业名称'),
  ('injection_order', '策略文档注入顺序'),
  ('input_end_date', '指标输入结束日期'),
  ('input_manifest', '回测输入数据清单'),
  ('input_modalities', '模型支持的输入模态列表'),
  ('input_row_count', '计算使用的输入行数'),
  ('input_sha256', '指标输入集合 SHA-256'),
  ('input_start_date', '指标输入开始日期'),
  ('input_summary', '分析或回测输入摘要'),
  ('input_tokens', '模型输入令牌数'),
  ('instrument_id', '关联市场标的标识'),
  ('intraday_md', '盘中执行预案 Markdown'),
  ('invalidation_md', '失效条件 Markdown'),
  ('is_new', '是否为上市新股'),
  ('is_open', '是否为开市日'),
  ('is_st', '是否为 ST 风险警示股票'),
  ('item_kind', '每日计划条目类型'),
  ('job_id', '关联作业定义标识'),
  ('job_run_id', '关联作业运行标识'),
  ('job_type', '作业执行类型'),
  ('kind', '记录类型'),
  ('ladder', '连板梯队原始结构'),
  ('last_error_summary', '会话最近一次错误摘要'),
  ('last_event_time', '最后一次触发涨跌停事件时间'),
  ('last_evolution_id', '最近一次已采纳策略演进记录标识'),
  ('last_verified_at', '记忆最近核验时间'),
  ('legacy_content_document_id', '关联旧内容库文档标识'),
  ('legacy_path', '退役文件来源路径'),
  ('lifecycle_status', '标的生命周期状态'),
  ('log', '作业运行日志'),
  ('low', '最低价'),
  ('ma10', '十周期移动平均值'),
  ('ma20', '二十周期移动平均值'),
  ('ma5', '五周期移动平均值'),
  ('ma60', '六十周期移动平均值'),
  ('macd_hist', 'MACD 柱状值'),
  ('manifest', '数据卷清单'),
  ('markdown', '版本化输出 Markdown 正文'),
  ('market_cap', '总市值'),
  ('market_domain_tools_enabled', '是否启用市场领域工具'),
  ('market_value', '持仓市值'),
  ('max_seal_money', '当日最大封单金额'),
  ('max_tokens', '模型单次最大输出令牌数'),
  ('member_instrument_id', '板块成员标的标识'),
  ('methodology', '固定评分基准研究方法'),
  ('metrics', '旧回测指标结构'),
  ('metrics_json', '回测结构化指标'),
  ('metrics_summary', '竞价核心指标摘要'),
  ('mime_type', '附件媒体类型'),
  ('missing_md', '计划尚缺条件 Markdown'),
  ('model_id', '关联模型标识'),
  ('model_key', '服务商模型代码'),
  ('name', '名称'),
  ('net_amount', '榜单净买入金额'),
  ('net_profit', '净利润'),
  ('next_retry_at', '下次允许重试时间'),
  ('note', '补充说明'),
  ('notes', '回测备注'),
  ('open', '开盘价'),
  ('open_count', '盘中开板次数'),
  ('opened_at', '当前持仓周期开始日期'),
  ('opened_fetch_run_id', '建立成分关系的抓取运行标识'),
  ('operating_cashflow', '经营活动现金流'),
  ('outline', '策略演进讨论提纲'),
  ('output_dir', '退役兼容的回测输出目录'),
  ('output_sha256', '外部命令输出 SHA-256'),
  ('output_tokens', '模型输出令牌数'),
  ('output_type', '作业输出类型'),
  ('parent_session_id', '父会话标识'),
  ('path', '本地文件路径'),
  ('payload', '确认请求或数据快照载荷'),
  ('pb', '市净率'),
  ('pe_ttm', '滚动市盈率'),
  ('pending_realized_pnl', '当前持仓周期待结转的部分卖出已实现盈亏'),
  ('plan_output_id', '关联每日计划输出标识'),
  ('playbook_item_id', '关联每日计划条目标识'),
  ('pnl_amount', '持仓浮动盈亏金额'),
  ('pool', '标的池类型'),
  ('precision', '账户快照精度等级'),
  ('price', '成交或事件价格'),
  ('price_lower', '执行价格下界'),
  ('price_upper', '执行价格上界'),
  ('priority', '计划条目优先级'),
  ('produced_artifacts', '旧任务产生的产物列表'),
  ('progress', '回测执行进度百分比'),
  ('prompt', '外部命令提示词'),
  ('prompt_id', '关联作业提示词标识'),
  ('prompt_revision_id', '本次运行固化的提示词修订标识'),
  ('proposal_id', '产生修订的发布提案标识'),
  ('proposed_changes', '提议的结构化策略变更'),
  ('provider_id', '关联模型服务商标识'),
  ('provider_key', '模型服务商代码'),
  ('ps_ttm', '滚动市销率'),
  ('quantity', '持仓或成交数量'),
  ('range_days', '龙虎榜统计区间天数'),
  ('raw_summary', '上游原始摘要'),
  ('raw_text', '账户快照原始文本'),
  ('realized_pnl', '本笔卖出已实现毛盈亏'),
  ('reason', '产生记录或状态的原因'),
  ('reasoning', '模型推理能力配置'),
  ('reasoning_tokens', '模型推理令牌数'),
  ('relation', '两个回测运行的关系类型'),
  ('report_path', '退役兼容的回测报告路径'),
  ('report_period', '财务报告期'),
  ('request_json', '领域请求参数'),
  ('request_key', '规范化请求唯一键'),
  ('request_params', '规范化请求参数'),
  ('requires_human', '是否必须由真实用户决策'),
  ('research_outline', '回测研究提纲'),
  ('result', '确认执行结果'),
  ('result_bytes', '工具结果字节数'),
  ('result_json', '领域分析结构化结果'),
  ('result_md', '兼容保留的作业 Markdown 结果'),
  ('result_rows', '工具结果行数'),
  ('result_sha256', '工具结果 SHA-256'),
  ('retention_status', '回测源码保留状态'),
  ('revenue', '营业收入'),
  ('review_type', '集合竞价复核类型'),
  ('revision_no', '修订序号'),
  ('risk_md', '风险提示 Markdown'),
  ('roe', '净资产收益率'),
  ('role', '角色类型'),
  ('row_count', '数据记录行数'),
  ('rows_written', '本次实际写入行数'),
  ('rsi14', '十四周期相对强弱指标'),
  ('run_id', '关联运行标识'),
  ('run_key', 'Agent 运行唯一键'),
  ('run_metric_id', '关联 Agent 运行指标标识'),
  ('sample_counts', '各评分特征样本数'),
  ('scheduled_for', '作业计划触发时间'),
  ('scope', '抓取或记忆适用范围'),
  ('score', '研究评分'),
  ('script_id', '关联旧脚本标识'),
  ('sdk_version', '回测使用的 SDK 版本'),
  ('seal_money', '收盘封单金额'),
  ('sector_code', '旧版行业代码'),
  ('sell_amount', '榜单卖出金额'),
  ('seq', '会话内消息序号'),
  ('sequence_no', '工具调用顺序号'),
  ('service_version', '领域服务实现版本'),
  ('session_id', '关联 Agent 会话标识'),
  ('session_status', '会话运行状态'),
  ('session_type', '会话类型'),
  ('sha256', '内容 SHA-256'),
  ('singleton', '单例记录约束标记'),
  ('size_bytes', '附件或源码字节数'),
  ('snap_date', '快照日期'),
  ('sort', '展示排序值'),
  ('source', '数据或记录来源'),
  ('source_asset_type', '上游资产类型'),
  ('source_code', '版本化回测源码正文'),
  ('source_job_run_id', '来源每日计划作业运行标识'),
  ('source_kind', '旧内容来源类型'),
  ('source_mtime', '旧来源文件修改时间'),
  ('source_path', '旧来源文件路径'),
  ('source_payload', '上游原始记录载荷'),
  ('source_row_sha256', '上游单行数据 SHA-256'),
  ('source_run_id', '记忆来源运行标识'),
  ('source_run_type', '记忆来源运行类型'),
  ('source_session_id', '来源 Agent 会话标识'),
  ('source_sha256', '来源内容 SHA-256'),
  ('source_size_bytes', '回测源码字节数'),
  ('source_summary', '评分基准来源摘要'),
  ('source_time', '上游数据时间'),
  ('source_timestamp_ms', '上游数据时间戳毫秒值'),
  ('source_updated_at', '上游记录更新时间'),
  ('stage', '策略阶段'),
  ('started_at', '运行开始时间'),
  ('status', '记录或运行状态'),
  ('steps', '旧任务执行步骤列表'),
  ('stock_character', '标的股性摘要'),
  ('stop_loss_mode', '止损执行模式'),
  ('stop_price', '止损价格'),
  ('strategy_change_seq', '运行固化的策略变更序号'),
  ('strategy_hash_after', '演进结论采纳后的策略集合哈希'),
  ('strategy_hash_before', '演进开始前的策略集合哈希'),
  ('strategy_snapshot_hash', '运行固化的策略集合哈希'),
  ('strategy_state_revision', '会话启动时的策略变更序号'),
  ('strategy_state_sha256', '会话启动时的策略集合哈希'),
  ('streak_count', '连续涨停板数量'),
  ('summary', '摘要'),
  ('superseded_by_run_id', '替代当前结论的后续回测运行标识'),
  ('supersedes_id', '被当前记忆替代的旧记忆标识'),
  ('supersedes_output_id', '被当前输出替代的旧输出标识'),
  ('synced_at', '旧版本同步时间'),
  ('tags', '标签列表'),
  ('target_date', '任务或计划目标日期'),
  ('target_id', '旧内容导入目标记录标识'),
  ('target_price', '目标价格'),
  ('target_table', '旧内容导入目标表名'),
  ('task_definition_id', '关联旧任务定义标识'),
  ('task_run_id', '关联旧任务运行标识'),
  ('template_path', '旧任务模板路径'),
  ('template_sha256', '旧任务模板 SHA-256'),
  ('through_created_at', '历史基线覆盖到的事件创建时间'),
  ('ticker', '不含交易所后缀的证券代码'),
  ('timed_out', '外部命令是否超时'),
  ('title', '标题'),
  ('tool_call_id', '模型工具调用标识'),
  ('tool_config', '评测使用的工具配置'),
  ('tool_name', '工具名称'),
  ('total_asset', '账户总资产'),
  ('total_ms', 'Agent 运行总耗时毫秒数'),
  ('total_pages', '上游数据总分页数'),
  ('trade_date', '交易日期'),
  ('training_end', '评分基准训练结束日期'),
  ('training_start', '评分基准训练开始日期'),
  ('trigger_kind', '手动或定时触发类型'),
  ('truncated', '工具结果是否被截断'),
  ('turnover', '成交额'),
  ('updated_at', '记录最近更新时间'),
  ('version', '数据库迁移版本号'),
  ('version_no', '内容版本序号'),
  ('versioned_at', '回测源码固化时间'),
  ('volume', '成交量'),
  ('volume_unit', '成交量单位'),
  ('web_research_enabled', '是否启用联网研究工具'),
  ('worker_version', '回测工作器版本'),
  ('yolo_mode', '是否允许免确认执行普通写操作');

DO $$
DECLARE
  missing_names text;
  item record;
BEGIN
  SELECT string_agg(name, ', ' ORDER BY name)
    INTO missing_names
    FROM (
      SELECT DISTINCT attribute.attname AS name
        FROM pg_class relation
        JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
        JOIN pg_attribute attribute
          ON attribute.attrelid = relation.oid
         AND attribute.attnum > 0
         AND NOT attribute.attisdropped
        LEFT JOIN _column_comment description ON description.column_name = attribute.attname
       WHERE namespace.nspname = 'public'
         AND relation.relkind IN ('r', 'p')
         AND description.column_name IS NULL
    ) missing;
  IF missing_names IS NOT NULL THEN
    RAISE EXCEPTION '数据库字段注释词典缺少：%', missing_names;
  END IF;

  FOR item IN
    SELECT relation.oid, relation.relname, attribute.attnum, attribute.attname,
           description.description
      FROM pg_class relation
      JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
      JOIN pg_attribute attribute
        ON attribute.attrelid = relation.oid
       AND attribute.attnum > 0
       AND NOT attribute.attisdropped
      JOIN _column_comment description ON description.column_name = attribute.attname
     WHERE namespace.nspname = 'public' AND relation.relkind IN ('r', 'p')
  LOOP
    IF col_description(item.oid, item.attnum) IS NULL THEN
      EXECUTE format(
        'COMMENT ON COLUMN public.%I.%I IS %L',
        item.relname,
        item.attname,
        item.description
      );
    END IF;
  END LOOP;
END $$;
